language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: EN4leQXqFqHwSWRJ/VP/DrgIFUURhMc7HZvOGq7wzxI4gGWAmwrdLZiXLtNMBGGSbCNiLYdctI35YE5RoHLn0SIC9vDiVq5uWWAd7JR1l6yPfvs+aupmekDUuGzIB+iczsCd+SWqckEhaa2DXZEfQbFyxyCgtRyxLOIRYn3KpixsyczEOvWR7VdKqo5os2Z8fGN0KRfGxoaKCFy5ye5ufcku53w5M002SNJM9OgJ5HRSv8b1nczDWpUSonR2XInEHakW7RctznT4UFgMI5BGoP0MLNBMAygtgcrPF72qDB2kRfJ63SostNxrD46wrvEjWBLvanx4LV8vYy18XXNBJV6KlLvwl5725zutM8S3ryYBNHc+ZX+CZQScVnlFLMbzaUyg23pyRwnktObe7Cgd6XMNqgnSYhbWVTBPWJFtCzo3jd9RD9B8mmrFGI/J1QU8g0IPU4SuCm3f2M8lvCkope9go0GUU26pa0ax9niERpN+sOBUvdI/65hRFLAwFiuPFQJSNsfAynvfMLJCRZJNEhsu5ieRd4Dm1zof+fA5Y/vhMpB+CnLgEON7nWzkBqa680hpltTA/4DZ1QvXNNqfC/2n3Nf83kach+2FzKH5Ut2VPdYN88tvY82vwRHy/9JAB3W6+f9Fw1TOCh2FWwYBRkGxFK/gaaRKCd034pkPd+I=
  - secure: YTZ40PyvU/2IW3hfl15mzjtT3jH2IBI5SegMESTsHJqSLuvATe5tmncaTCUU8atu78qFSJlvshnSHZ+5Gpx3AgJb6IVMl5c6MMhZHcOTDFV+ZJCX2la8sGnMN+MbcP/YXpBg1l9iiMVpGPFrWz9lKPVxdugFVFWN5y4KdUcWXqjA6v1tEUn7Kj8WiZ8uD+bJaLBtv0jgAXSRJuyqkx9WrZbZtTIDypfwusad90UwuTJh6icQLL5BWiCHFek+tkEBy1GNcNmn2HfcIGEXP0Kb1bYS9J07vLUTMHevyxJsb3Tu8vfhjN3/UXY4++IF48CGdJq+0BYXk0BsKwNEOH7stILVKHLo0fGBFH8+LflcfSLuiAlaPX0ug/Qgotum/vPNl6Swelyc0MFcTq//65zlDV0FM+HU6NVVZwQoU+TNuxpuitMwVVCxKYM3r447jwZlwsMi7jBxYjNFcFRYSTq+mR2HDiktXK0B8Eg3rSN9ljx11d8wErILQ6l+HB6s1qMUx3pZOHs499+BjoNEAF0nQ8J0oqe4XMFi7Q+ou+4F+0ZCr/Qaf9C1HCDm+owOCW4HUi8opRDkV8/H5N5DXs8uImdZpo3taVLgIOYxqbhQ5e2/Byro4uoTRexwOQfPAmmGShvq3qwCcbKj/SwRWzY2UhmQHeV12MhS4OEi9xVjQ/8=
sudo: false
