language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: t1YBFPUnVxcTvmgP5xVxwOPtwHrdbs4oD6zAvFHA56xaA4Y04qEcgVrLmTguv4kDjIai583ud0n/RRglh5rZ8x8eJk1m1JlKdf0qwdKttavDDpallvmCh06YcMBhrYrAtaNtHQQc7pRY6r2urMxq7csfM1DoJXLDaWoXq0cZG+uMjsjZSpJA1dCwo+l473h+KS6DgoOAwREgiQkdxq0cjXFV+iXqEyy0Kq31wZs/ZKzJp0hyO5KRrcf/crixEQKoJOI59SI5MFqmYCSfv0KLXuGq6jtp7wpbcHwxj13lUQjHw1i2BQJOLNpPTXlofRv52Bui9NTVIiw5ggdywQ0JdNqo9OE7sAlNph1wdjWRunI6uut9YOBj1YRTgyVjcAZWVN2w7OJDVIAauPq6jKssucknmyWbjE83Szz4O5vwIQLR4w3Xvvx1chwfX48KthHQXTeZkte1fYZGiS05VxXINqEb0DVrv4xnGq2gfIPzP6lJFSrVxNCwuOUPKj4LUYChrrTM8V57buvObWgBhN0IxzeyGdlnT2g379C5T9KmVi+qPuu+XZnocKYgXxcymJB6SXFJlc2+rj2fA7aKSMAnuvMAUrhRUGZr+w7b5So6AGzK/UkoPOEgXZS3pEJ5/Qmd0iz+FfMGkIRMKplBYvAmvuViYd9Ra244UrVVuKHej7s=
  - secure: sHQGJRPa8CtTte5XUFMDjAPBTcNSIWyKk6Ke4SaBQ3xT9+3Vtf1i6KV9XvdveCpYODU8CvMP8Dd2TWoxAeLExyZUWgv/DnnUIq//0HvDfex/ELlgPwT9L3zzThotaQUfK2fO+miSc4/s0OnhHIuOgf/KcJL/eZcwVX+1K35htj0vXNa21168HzcTcGKZ0eVKeHZY3lrzv+PANCpCdoDOZBEVieLWNw62sUeBWUuYhYg3WPKNWCm69mXpLrJSQ/Pt7Q3znq+aRY6EfAre3Y9FVkdtKVPsaM2OMlOUdBPSD70sF8MdXmVZzP98eJHHeYtdPS5pqZgIjrL4ItR0VP4K2LtOpTnC5qGV9gO/4L4sYjb06zr0Y+H4i878cBARErv8LkWkZ5caq++PWRdJVRStzTyDW+t+kGA/1xAybAYs2oGqv/zNldglIP/ZTa8QVnuR+OWfD8WyiSglAEOGH0QNamEVD5JvC8Cc7B0DdqEzpnXnY1UX05pi6f51SM/d51N4AtCZUSX+oobZSENGk9HlS7bVCcmRpPa7hNiLb7GCtx3TKrhQ9YwEny07mt9EVmol3iqgq/vWliY55SX9WmTHoUFfadKEfFCc9ztdq5j0PyNKvbUCXJBmlMD8svkgkBWp7dZO9A5ih5nd0pyAFJq1yN0/YQx1nuTfsDKoTViBr/c=
