language: java
jdk:
- openjdk7
- oraclejdk8
before_install:
- cp ./etc/settings.xml ~/.m2/
- cp ./etc/onFailure.sh  ~/
- cp ./etc/onSuccess.sh  ~/
- chmod 777 ~/onFailure.sh
- chmod 777 ~/onSuccess.sh
script:
- mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
after_script:
- mvn -B cobertura:cobertura coveralls:report
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#lightblue
  on_success: always
env:
  global:
  - secure: pnwFMPGmG2KX1Y7Tzd0WQCzkj+X/92vVig/fiAe+5SdHTpUtPU2kIYugVxJz1pTpCas0/AK2sHTOvHiuY0QtjJXZzoU3wQ2r4Fil1kqXoIg7qtnRtPViKQt07/MRfrNh6pJuaDUESCv0YD8VIiv0sReGw6hLD8g5jK5RJZo+PGZMEup9kA4AhJ1o6dcHBJELqcfxvPmBGAffQtus41HvMxXK/Ok5a1fjizm02BxrKSRsOWPpX5TFBY7vC6UXrPJ3ow0tgMCMt0U1cE56Ti4WXx2GviGT5c5zRdIWcP/k3O39pmQZKxTNjo/X/wEKqBpitJ8BjZ+QBWZPDwdPDccri296xV38v93AuBJBdOEl2Wb318WvuMHFUbwUfVMKw0t/nBFu8dPVpael2Qivylu5fmJ5gwLVUn/n8ufkLaKqGKhfCrmz/jCQfc/wVPEn8bXeR1TOsWcNvtm9F+lTimrAzdrzzCDJ/NRmE7DjpLcJ9HZ8witNsNepKaE1d+T1LgHw97aUXuDHJpRy32KLpBm63amXr3iO7JYH4LdDBVuFMsmBF3W7Hi7eDxKw3phfGG2Lwkl5vdPswDfZxruwHqE9ZfUW3hJ5UL9ADvoLskmfI3sN3lYZwr43/TIyoKs4iwao2aGlbPAUhpHj/itl1Xkty17lHxu8BwJ0nSc7+lENLMY=
  - secure: V5bnDfL0Di8iNGav/PiF6X7e1AtNH+rBvzXpmgHUJwA6UbjTNRVgCF8/B2lLTLYFPTg8jBTeBhNxItG0BJl4gi7QIT1zeJSwlijKsKefcp5B3FAR0Yi/7Idobq1WVmrxUqPzti2AWibxC1e9ij6KOhDLnCPzmUkeDSJhqdLrwwIM6GIdjgE6RUM58otI/0e7ubpkiCqxOoQaWhsDf4uaQx+cdQgIoEmbCsPHU04xqDNBNl1S2DJ8RmwM2LqPt7qiiELakweHuv19YkEOyDeX3DMDEtnLfR+P3ymdVKbC/aOmZAIu+LSHKcpm3g0OTZtCipOPhIzl5hc1mnPlptvYYi4ABul4q2jJaZECBKXxjDCenqAXTK9pW4J14X5DRLXsTFI1IE8CpD6Ve/60YODEBYSX7vDsHxmz30pS4wL5zEIbtyYsZYgUTeJf/CwO/hO1wDbJ+GyOP1Fwazn14Ms3ziR6KHID3t5Z2IXtBiu8a70zKSAL5lltDpUy6e/YQxJNvlrUl6LqVK+esdGjAEWZeOIOCuU0S6/CzS3fgTkFV4ahjod6YNRVzgYCu77nSvg919v9ejgO2pguTxUyMVwP7EZlqRGn8+muJhnbKTbzlCB94G+xxGLEaUAXDweN6weJ94WYfXWGo/b6VVn4AiQBM1XJluiZY7aRvni854DZ1H0=
